### ISSUE TITLE
Test failure with numpy 1.10.4

### ISSUE THREAD

**Issue by rekado** [ukoethe/vigra#326]
One of Vigra's tests fail when building with numpy 1.10.4:

~~~
Running vigranumpy tests
cd /tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/test && ./run_vigranumpytest.sh

executing test file /tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/test/test1.py
......
executing test file /tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/test/test2.py
..........
executing test file /tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/test/test3.py
......
executing test file /tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/test/test_arraytypes.py
......................E.
executing test file /tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/test/test_color.py
..
executing test file /tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/test/test_impex.py
...
======================================================================
ERROR: test_arraytypes.testMethods
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/qdi2y0wfl4lj70f7cgnnvsgwppnadz03-python2-nose-1.3.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/test/test_arraytypes.py", line 1331, in testMethods
    nz = n.nonzero()
  File "/tmp/guix-build-vigra-1.10.0.drv-0/build/vigranumpy/vigra/arraytypes.py", line 1285, in nonzero
    res[k].axistags = AxisTags(AxisInfo(self.axistags[k]))
AttributeError: 'numpy.ndarray' object has no attribute 'axistags'

----------------------------------------------------------------------
Ran 51 tests in 3.212s

FAILED (errors=1)
~~~

(See complete build log here: http://hydra.gnu.org/build/1008323/log/raw)

We did not see this error before upgrading numpy.  The latest successful build used numpy 1.9.1.  The full build log can be seen here: http://hydra.gnu.org/build/1000397/log/raw

**Comment by ukoethe** [comment]
I think the problem has already been solved in branch `version-1-11-rc`. Can you please confirm if this is true?

**Comment by rekado** [comment]
Thanks.  According to Andreas this should be okay now: https://mailhost.informatik.uni-hamburg.de/pipermail/vigra/2016-February/001325.html
