### ISSUE TITLE
Error on attempting to import vigra.pyqt

### ISSUE THREAD

**Issue by DManowitz** [ukoethe/vigra#539]
When I attempt to import vigra.pyqt, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\vigra\pyqt\__init__.py", line 36, in <module>
    import quickdialog
ModuleNotFoundError: No module named 'quickdialog'
```

**Comment by k-dominik** [comment]
Hi @DManowitz,

thank you very much!

It looks like these parts of vigra have to be ported both to Python3 (relative imports) and support at least `PyQt5` (in the code it is still using `PyQt4` which is severely outdated).
